[package]
name = "tex_to_speech_core"
version = "0.1.0"
edition = "2024"

[dependencies]
latex2mathml = "0.2.3"
log = "0.4.28"
thiserror = "2"

[dependencies.mathcat]
path = "../third_party/MathCAT"
features = ["include-zip"]
